WebGuide/Controllers/ProfileController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebGuide.Data;
using WebGuide.Models;
using WebGuide.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace WebGuide.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly GoogleCloudStorageService _storage;

        public ProfileController(ApplicationDbContext context, GoogleCloudStorageService storage)
        {
            _context = context;
            _storage = storage;
        }

        public async Task<IActionResult> Index()
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

            var tasksCount = await _context.Tasks.CountAsync(t => t.UserId == user.Id);

            var model = new ProfileModel
            {
                Username = user.Username,
                Email = user.Email,
                CreatedAt = user.CreatedAt,
                TasksCount = tasksCount,
                ExistingImageUrl = user.ProfileImageUrl
            };

            ViewBag.GoogleAuthorized = HttpContext.Session.GetString("GoogleAccessToken") != null;
            
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit()
        {
            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

            var model = new ProfileModel
            {
                Username = user.Username,
                Email = user.Email,
                ExistingImageUrl = user.ProfileImageUrl
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProfileModel model)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage);
                foreach (var error in errors)
                {
                    Console.WriteLine(error);
                }

                return View(model);
            }

            var email = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

            user.Username = model.Username;
            user.Email = model.Email;

            if (model.ProfileImage != null && model.ProfileImage.Length > 0)
            {
                var fileUrl = await _storage.UploadFileAsync(model.ProfileImage.OpenReadStream(), model.ProfileImage.FileName, model.ProfileImage.ContentType);
                user.ProfileImageUrl = fileUrl;
            }

            _context.Update(user);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAccount()
        {
            var email = User.FindFirstValue(ClaimTypes.Email);
            var user = await _context.Users.FirstOrDefaultAsync(u => u.Email == email);

            if (user != null)
            {
                _context.Users.Remove(user);
                await _context.SaveChangesAsync();

                await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ConfirmDelete()
        {
            return View();
        }

    }

}

WebGuide/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using WebGuide.Data;
using WebGuide.Models;
using WebGuide.Services;

namespace WebGuide.Controllers
{
    [Authorize]
    public class TasksController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly TrelloService _trelloService;
        private readonly ILogger<TasksController> _logger;

        public TasksController(ApplicationDbContext context, TrelloService trelloService, ILogger<TasksController> logger)
        {
            _context = context;
            _trelloService = trelloService;
            _logger = logger;
        }

        // GET: Tasks/Index
        public async Task<IActionResult> Index(string? sortBy, int? priorityFilter, [FromQuery] string? showCompleted)
        {
            var showCompletedBool = showCompleted == "true";
            ViewBag.ShowCompleted = showCompletedBool;

            var currentUserEmail = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;

            var tasksQuery = _context.Tasks
                .Include(t => t.User)
                .Where(t => t.User.Email == currentUserEmail)
                .AsQueryable();

            if (priorityFilter.HasValue)
                tasksQuery = tasksQuery.Where(t => t.Priority == priorityFilter.Value);

            if (!showCompletedBool)
            {
                var now = DateTime.UtcNow;
                tasksQuery = tasksQuery.Where(t => !t.IsCompleted && t.Deadline > now);
            }


            tasksQuery = sortBy switch
            {
                "priorityAsc" => tasksQuery.OrderByDescending(t => t.Priority),
                "priorityDesc" => tasksQuery.OrderBy(t => t.Priority),
                _ => tasksQuery.OrderBy(t => t.Deadline)
            };

            ViewBag.SortBy = sortBy;
            ViewBag.PriorityFilter = priorityFilter;

            var tasks = await tasksQuery.ToListAsync();
            return View(tasks);
        }

        // GET: Tasks/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var task = await _context.Tasks
                .Include(t => t.User)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (task == null)
                return NotFound();

            return View(task);
        }

        // GET: Tasks/Create
        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tasks/Create
        [HttpPost("Create")]
        [ValidateAntiForgeryToken]  //comment for TaskIntegrTest CreateTask_Should_SaveTaskInDatabase
        public async Task<IActionResult> Create(TaskEntity model, IFormFile? attachment)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState
                    .SelectMany(kv => kv.Value.Errors.Select(err => $"[{kv.Key}] {err.ErrorMessage}"))
                    .ToList();

                Console.WriteLine(" ModelState.Errors:");
                foreach (var err in errors)
                    Console.WriteLine(err);
            }

            var currentUserEmail = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.Email)?.Value;
            var currentUser = await _context.Users.FirstOrDefaultAsync(u => u.Email == currentUserEmail);
            if (currentUser != null)
            {
                model.UserId = currentUser.Id;
            }
            else
            {
                ModelState.AddModelError("", "Не вдалося визначити користувача.");
                return View(model);
            }

            //Google Cloud Storage
            if (attachment != null && attachment.Length > 0)
            {
                var googleStorageService = HttpContext.RequestServices.GetService<GoogleCloudStorageService>();
                using (var stream = attachment.OpenReadStream())
                {
                    var fileUrl = await googleStorageService.UploadFileAsync(stream, attachment.FileName, attachment.ContentType);
                    model.FileUrl = fileUrl;
                }
            }
            var kyivZone = TimeZoneInfo.FindSystemTimeZoneById("Europe/Kyiv");
            model.Deadline = DateTime.SpecifyKind(model.Deadline, DateTimeKind.Unspecified);
            model.Deadline = TimeZoneInfo.ConvertTimeToUtc(model.Deadline, kyivZone);
            _context.Tasks.Add(model);
            await _context.SaveChangesAsync();

            //Trello
            try
            {
                var trelloSuccess = await _trelloService.CreateCardAsync(model);
                if (!trelloSuccess)
                {
                    _logger.LogError("Не вдалося створити картку Trello для завдання з ID {TaskId}", model.Id);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Виникла помилка при створенні картки Trello для завдання з ID {TaskId}", model.Id);
            }

            //Mailjet
            try
            {
                var mailjetService = HttpContext.RequestServices.GetService<MailjetEmail>();

                var subject = "Нове завдання створено";
                var html = $@"
                    <h2>📌 Нова задача: <strong>{model.Title}</strong></h2>
                    <p><strong>Опис:</strong> {model.Description}</p>
                    <p><strong>Дедлайн:</strong> {model.Deadline:g}</p>
                    {(string.IsNullOrEmpty(model.FileUrl) ? "" : $"<p><strong>Файл:</strong> <a href='{model.FileUrl}'>Переглянути</a></p>")}
                        ";
                _logger.LogWarning(" Пошта має бути надіслана на {Email}", currentUser.Email);
                await mailjetService.SendEmailAsync(
                    toEmail: currentUser.Email,
                    toName: currentUser.Username,
                    subject: subject,
                    htmlContent: html
                );
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "❌ Помилка під час надсилання email через Mailjet.");
            }

            // Google Calendar
            if (model.AddToGoogleCalendar)
            {
                var accessToken = HttpContext.Session.GetString("GoogleAccessToken");

                if (!string.IsNullOrEmpty(accessToken))
                {
                    try
                    {
                        var calendarService = HttpContext.RequestServices.GetRequiredService<GoogleCalendarService>();
                        await calendarService.AddTaskToCalendarAsync(model, accessToken);
                        _logger.LogInformation("Подію додано в Google Календар");
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "Помилка при додаванні події до Google Календаря");
                    }
                }
                else
                {
                    _logger.LogWarning("Google токен відсутній — подію не додано до календаря");
                }
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Tasks/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var task = await _context.Tasks.FindAsync(id);
            if (task == null)
                return NotFound();

            return View(task);
        }

        // POST: Tasks/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TaskEntity model)
        {
            if (id != model.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(model);

            try
            {
                var existingTask = await _context.Tasks.FirstOrDefaultAsync(t => t.Id == id);
                if (existingTask == null)
                    return NotFound();

                var kyivZone = TimeZoneInfo.FindSystemTimeZoneById("Europe/Kyiv");
                model.Deadline = DateTime.SpecifyKind(model.Deadline, DateTimeKind.Unspecified);
                model.Deadline = TimeZoneInfo.ConvertTimeToUtc(model.Deadline, kyivZone);

                existingTask.Title = model.Title;
                existingTask.Description = model.Description;
                existingTask.Deadline = model.Deadline;
                existingTask.Priority = model.Priority;


                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TaskExists(model.Id))
                    return NotFound();
                else
                    throw;
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]  //comment for TaskIntegrTest Tasks_Complete_Should_SetIsCompletedToTrue
        public async Task<IActionResult> Complete(int id)
        {
            var task = await _context.Tasks.FirstOrDefaultAsync(t => t.Id == id);
            
            if (task == null)
                return NotFound();

            if (!task.IsCompleted)
            {
                task.IsCompleted = true;
                task.CompletedAt = DateTime.UtcNow;
                var completedLocal = task.CompletedAt?.ToLocalTime();

                _logger.LogInformation("✅ Завдання ID {Id} позначене як виконане о {Time}", task.Id, completedLocal);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Tasks/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

WebGuide/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebGuide.styles.css" asp-append-version="true" />
</head>
<body class="body">
    <div class="wrapper">
        <header class="container">
            <span class="logo">Tasker</span>
            <nav>
                <ul>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li> <a asp-controller="Tasks" asp-action="Index">📋 Завдання</a></li>
                        <li> <a asp-controller="Tasks" asp-action="Calendar">🗓 Календар</a></li>
                        <li> <a asp-controller="Statistics" asp-action="Index">📈 Статистика</a></li>
                        <li> <a asp-controller="Profile" asp-action="Index">👤 Профіль</a></li>
                        
                    }
                   else
                    {
                        <li><a href="/">Home</a></li>
                        <li><a href="/login">Login</a> </li>
                        <li><a href="/register">Register</a> </li>
                        <li class="navbutton"><a href="/login">Account</a></li>
                   }
                </ul>
            </nav>
        </header>

        <main style="min-height:750px;background: rgb(0,0,0);
    background: linear-gradient(180deg, rgba(0,0,0,1) 0%, rgba(26,14,1,1));">
            @RenderBody()
        </main>

        <footer>
            <div class="blocks container">
                <div>
                    <span class="logo">Tasker</span>
                    <p class="underlogo">Create - today, forget - forever</p>
                </div>
                <div>
                    <h4>Authors</h4>
                    <ul class="contact-icons">
                        <li>
                            <a href="https://discord.com/users/tvoisenpai" target="_blank" title="Discord">
                                <img src="https://cdn-icons-png.flaticon.com/512/5968/5968756.png" alt="Discord Icon" class="contact-icon">
                                <span>Discord</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://t.me/kinosura666" target="_blank" title="Telegram">
                                <img src="https://cdn-icons-png.flaticon.com/512/2111/2111646.png" alt="Telegram Icon" class="contact-icon">
                                <span>Telegram</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://t.me/kinosura666" target="_blank" title="Instagram">
                                <img src="https://cdn-icons-png.flaticon.com/512/15713/15713420.png" alt="Instagram Icon" class="contact-icon">
                                <span>Instagram</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/Kinosura666" target="_blank" title="GitHub">
                                <img src="https://cdn-icons-png.flaticon.com/512/25/25231.png" alt="GitHub Icon" class="contact-icon">
                                <span>Github</span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h4>Contact me</h4>
                    <ul class="contact-icons">
                        <li>
                            <a href="https://discord.com/users/tvoisenpai" target="_blank" title="Discord">
                                <img src="https://cdn-icons-png.flaticon.com/512/5968/5968756.png" alt="Discord Icon" class="contact-icon">
                                <span>Discord</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://t.me/kinosura666" target="_blank" title="Telegram">
                                <img src="https://cdn-icons-png.flaticon.com/512/2111/2111646.png" alt="Telegram Icon" class="contact-icon">
                                <span>Telegram</span>
                            </a>
                        </li>
                        <li>
                            <a href="https://mail.google.com/mail/?view=cm&fs=1&to=kornievskiy.leha@gmail.com" target="_blank" title="Instagram">
                                <img src="https://cdn-icons-png.flaticon.com/512/281/281769.png" alt="Gmail Icon" class="contact-icon">
                                <span>Gmail</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <hr>
            <p>Created by Kornievskiy Oleksiy 2025</p>
        </footer>
    </div>
</body>

</html>